package service

import "github.com/SANEKNAYMCHIK/mock-cbr/internal/models"

// Здесь приведены все валюты из последних xml ответов с предоставленного сервиса
// Все статические данные (названия, коды, номиналы и т.д.) вынесены в отдельную константную структуру
// Так как не влияют на логику и результат (ну и просто должно же быть соответствие настоящим данным),
// уникальными данными будут являться только значение курса валюты
// и единичная стоимость валюты
var baseCurrencies = []models.Valute{
	{
		ID:        "R01010",
		NumCode:   "036",
		CharCode:  "AUD",
		Nominal:   1,
		Name:      "Австралийский доллар",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01020A",
		NumCode:   "944",
		CharCode:  "AZN",
		Nominal:   1,
		Name:      "Азербайджанский манат",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01030",
		NumCode:   "012",
		CharCode:  "DZD",
		Nominal:   100,
		Name:      "Алжирских динаров",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01035",
		NumCode:   "826",
		CharCode:  "GBP",
		Nominal:   1,
		Name:      "Фунт стерлингов",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01060",
		NumCode:   "051",
		CharCode:  "AMD",
		Nominal:   100,
		Name:      "Армянских драмов",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01080",
		NumCode:   "048",
		CharCode:  "BHD",
		Nominal:   1,
		Name:      "Бахрейнский динар",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01090B",
		NumCode:   "933",
		CharCode:  "BYN",
		Nominal:   1,
		Name:      "Белорусский рубль",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01100",
		NumCode:   "975",
		CharCode:  "BGN",
		Nominal:   1,
		Name:      "Болгарский лев",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01105",
		NumCode:   "068",
		CharCode:  "BOB",
		Nominal:   1,
		Name:      "Боливиано",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01115",
		NumCode:   "986",
		CharCode:  "BRL",
		Nominal:   1,
		Name:      "Бразильский реал",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01135",
		NumCode:   "348",
		CharCode:  "HUF",
		Nominal:   100,
		Name:      "Форинтов",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01150",
		NumCode:   "704",
		CharCode:  "VND",
		Nominal:   10000,
		Name:      "Донгов",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01200",
		NumCode:   "344",
		CharCode:  "HKD",
		Nominal:   1,
		Name:      "Гонконгский доллар",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01210",
		NumCode:   "981",
		CharCode:  "GEL",
		Nominal:   1,
		Name:      "Лари",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01215",
		NumCode:   "208",
		CharCode:  "DKK",
		Nominal:   1,
		Name:      "Датская крона",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01230",
		NumCode:   "784",
		CharCode:  "AED",
		Nominal:   1,
		Name:      "Дирхам ОАЭ",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01235",
		NumCode:   "840",
		CharCode:  "USD",
		Nominal:   1,
		Name:      "Доллар США",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01239",
		NumCode:   "978",
		CharCode:  "EUR",
		Nominal:   1,
		Name:      "Евро",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01240",
		NumCode:   "818",
		CharCode:  "EGP",
		Nominal:   10,
		Name:      "Египетских фунтов",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01270",
		NumCode:   "356",
		CharCode:  "INR",
		Nominal:   100,
		Name:      "Индийских рупий",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01280",
		NumCode:   "360",
		CharCode:  "IDR",
		Nominal:   10000,
		Name:      "Рупий",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01300",
		NumCode:   "364",
		CharCode:  "IRR",
		Nominal:   100000,
		Name:      "Иранских риалов",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01335",
		NumCode:   "398",
		CharCode:  "KZT",
		Nominal:   100,
		Name:      "Тенге",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01350",
		NumCode:   "124",
		CharCode:  "CAD",
		Nominal:   1,
		Name:      "Канадский доллар",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01355",
		NumCode:   "634",
		CharCode:  "QAR",
		Nominal:   1,
		Name:      "Катарский риал",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01370",
		NumCode:   "417",
		CharCode:  "KGS",
		Nominal:   100,
		Name:      "Сомов",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01375",
		NumCode:   "156",
		CharCode:  "CNY",
		Nominal:   1,
		Name:      "Юань",
		Value:     "",
		VunitRate: "",
	},
	{
		ID:        "R01395",
		NumCode:   "192",
		CharCode:  "CUP",
		Nominal:   10,
		Name:      "Кубинских песо",
		Value:     "",
		VunitRate: "",
	},
}
